export const CONFIG_KEYS = {
    DB: {
        MONGODB_URI: 'MONGODB_URI',
    },
    ADMIN: {
        ADMIN_USERNAME: 'ADMIN_USERNAME',
        ADMIN_PASSWORD: 'ADMIN_PASSWORD',
        ADMIN_COOKIE_NAME: 'ADMIN_COOKIE_NAME',
        ADMIN_COOKIE_PASSWORD: 'ADMIN_COOKIE_PASSWORD',
        ADMIN_SECRET: 'ADMIN_SECRET'
    }
}