export const CONFIG_KEYS = {
    DB: {
        MONGODB_URI: 'MONGODB_URI',
    },
    ADMIN: {
        ADMIN_USERNAME: 'ADMIN_USERNAME',
        ADMIN_PASSWORD: 'ADMIN_PASSWORD',
        ADMIN_COOKIE_NAME: 'ADMIN_COOKIE_NAME',
        ADMIN_COOKIE_PASSWORD: 'ADMIN_COOKIE_PASSWORD',
        ADMIN_SECRET: 'ADMIN_SECRET'
    },
    MESH: {
        MAX_MESH_SIZE_MB: 'MAX_MESH_SIZE_MB',
        CACHE_MESHES: 'CACHE_MESHES',
    },
    COSTS: {
        COST_PER_HOUR: 'COST_PER_HOUR',
        FIXED_COST: 'FIXED_COST',
        // In cubic millimeters per second
        AVERAGE_PRINT_SPEED: 'AVERAGE_PRINT_SPEED',
    },
    CURRENCY: {
        MONEY_FORMAT: 'MONEY_FORMAT',
        EXCHANGE_RATE_API_KEY: 'EXCHANGE_RATE_API_KEY',
    }
}